# Generated by Django 2.2.1 on 2019-05-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PR', 'Processadores'), ('MR', 'Memoria RAM'), ('DR', 'Disco Rigido/SSD'), ('PV', 'Placa de Video'), ('GA', 'Gabinete'), ('PM', 'Placa Mae'), ('FO', 'Fonte')], max_length=2, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descricao')),
            ],
        ),
    ]
