# Generated by Django 2.2.1 on 2019-05-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_quantidadeinicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidadeInicial',
        ),
    ]
