# Generated by Django 2.2.1 on 2019-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20190524_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidadeInicial',
            field=models.IntegerField(verbose_name='Quantidade Inicial'),
        ),
    ]
