# Generated by Django 2.2.1 on 2019-05-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20190524_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidadeInicial',
            field=models.IntegerField(serialize=False, verbose_name='Quantidade Inicial'),
        ),
    ]
