# Generated by Django 2.2.1 on 2019-05-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoRigido', models.ForeignKey(limit_choices_to={'categoria': 'DR'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Estoque')),
                ('fonte', models.ForeignKey(limit_choices_to={'categoria': 'FO'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Estoque')),
                ('gabinete', models.ForeignKey(limit_choices_to={'categoria': 'GA'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Estoque')),
                ('memoria', models.ForeignKey(limit_choices_to={'categoria': 'MR'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Estoque')),
                ('placaDeVideo', models.ForeignKey(limit_choices_to={'categoria': 'PV'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Estoque')),
                ('placaMae', models.ForeignKey(limit_choices_to={'categoria': 'PM'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Estoque')),
                ('processador', models.ForeignKey(limit_choices_to={'categoria': 'PR'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Estoque')),
            ],
        ),
    ]
