# Generated by Django 2.2.1 on 2019-05-04 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='discoRigido',
            field=models.ForeignKey(limit_choices_to={'categoria': 'DR'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fonte',
            field=models.ForeignKey(limit_choices_to={'categoria': 'FO'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='gabinete',
            field=models.ForeignKey(limit_choices_to={'categoria': 'GA'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='memoria',
            field=models.ForeignKey(limit_choices_to={'categoria': 'MR'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='placaDeVideo',
            field=models.ForeignKey(limit_choices_to={'categoria': 'PV'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='placaMae',
            field=models.ForeignKey(limit_choices_to={'categoria': 'PM'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='processador',
            field=models.ForeignKey(limit_choices_to={'categoria': 'PR'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.Produto'),
        ),
    ]
