# Generated by Django 2.2.1 on 2019-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PR', 'Pedido Realizado'), ('SE', 'Separacao em Estoque'), ('EM', 'Em Montagem'), ('RT', 'Realizacao de Testes'), ('CO', 'Concluido')], default='PR', max_length=2, verbose_name='Status'),
        ),
    ]
