# Generated by Django 2.2.1 on 2019-05-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20190521_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
    ]
